[package]
name = "unixsock"
version = "0.1.0"
authors = ["benaryorg <binary@benary.org>"]

[dependencies]
unix_socket = "0.5"
daemonize = "0.1"
log = "0.3"
flexi_logger = "0.3"
threadpool = "0.1"
atom = "0.3"

